services:
  - type: web
    name: go-from-scratch-project-278
    runtime: docker
    plan: free
    healthCheckPath: /ping
    autoDeploy: true
    envVars:
      - key: PORT
        value: 80
      - key: DATABASE_URL
        sync: false
      - key: BASE_URL
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: SENTRY_ENVIRONMENT
        value: production
