// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: links.sql

package sqlc

import (
	"context"
	"time"
)

const countLinkVisits = `-- name: CountLinkVisits :one
SELECT count(*)
FROM link_visits
`

func (q *Queries) CountLinkVisits(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinkVisits)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countLinks = `-- name: CountLinks :one
SELECT count(*)
FROM links
`

func (q *Queries) CountLinks(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLinks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLink = `-- name: CreateLink :one
INSERT INTO links (original_url, short_name)
VALUES ($1, $2)
RETURNING id, original_url, short_name, created_at
`

type CreateLinkParams struct {
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

type CreateLinkRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error) {
	row := q.db.QueryRowContext(ctx, createLink, arg.OriginalUrl, arg.ShortName)
	var i CreateLinkRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const createLinkVisit = `-- name: CreateLinkVisit :one
INSERT INTO link_visits (link_id, ip, user_agent, referer, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, link_id, ip, user_agent, referer, status, created_at
`

type CreateLinkVisitParams struct {
	LinkID    int64  `json:"link_id"`
	Ip        string `json:"ip"`
	UserAgent string `json:"user_agent"`
	Referer   string `json:"referer"`
	Status    int32  `json:"status"`
}

func (q *Queries) CreateLinkVisit(ctx context.Context, arg CreateLinkVisitParams) (LinkVisit, error) {
	row := q.db.QueryRowContext(ctx, createLinkVisit,
		arg.LinkID,
		arg.Ip,
		arg.UserAgent,
		arg.Referer,
		arg.Status,
	)
	var i LinkVisit
	err := row.Scan(
		&i.ID,
		&i.LinkID,
		&i.Ip,
		&i.UserAgent,
		&i.Referer,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :execrows
DELETE FROM links
WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteLink, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getLink = `-- name: GetLink :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE id = $1
`

type GetLinkRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetLink(ctx context.Context, id int64) (GetLinkRow, error) {
	row := q.db.QueryRowContext(ctx, getLink, id)
	var i GetLinkRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const getLinkByShortName = `-- name: GetLinkByShortName :one
SELECT id, original_url, short_name, created_at
FROM links
WHERE short_name = $1
`

type GetLinkByShortNameRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) GetLinkByShortName(ctx context.Context, shortName string) (GetLinkByShortNameRow, error) {
	row := q.db.QueryRowContext(ctx, getLinkByShortName, shortName)
	var i GetLinkByShortNameRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}

const listLinkVisits = `-- name: ListLinkVisits :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
ORDER BY id
`

func (q *Queries) ListLinkVisits(ctx context.Context) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, listLinkVisits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinkVisitsPage = `-- name: ListLinkVisitsPage :many
SELECT id, link_id, ip, user_agent, referer, status, created_at
FROM link_visits
ORDER BY id
LIMIT $2::bigint
OFFSET $1::bigint
`

type ListLinkVisitsPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageLimit  int64 `json:"page_limit"`
}

func (q *Queries) ListLinkVisitsPage(ctx context.Context, arg ListLinkVisitsPageParams) ([]LinkVisit, error) {
	rows, err := q.db.QueryContext(ctx, listLinkVisitsPage, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LinkVisit
	for rows.Next() {
		var i LinkVisit
		if err := rows.Scan(
			&i.ID,
			&i.LinkID,
			&i.Ip,
			&i.UserAgent,
			&i.Referer,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinks = `-- name: ListLinks :many
SELECT id, original_url, short_name, created_at
FROM links
ORDER BY id
`

type ListLinksRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListLinks(ctx context.Context) ([]ListLinksRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksRow
	for rows.Next() {
		var i ListLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksPage = `-- name: ListLinksPage :many
SELECT id, original_url, short_name, created_at
FROM links
ORDER BY id
LIMIT $2::bigint
OFFSET $1::bigint
`

type ListLinksPageParams struct {
	PageOffset int64 `json:"page_offset"`
	PageLimit  int64 `json:"page_limit"`
}

type ListLinksPageRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListLinksPage(ctx context.Context, arg ListLinksPageParams) ([]ListLinksPageRow, error) {
	rows, err := q.db.QueryContext(ctx, listLinksPage, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinksPageRow
	for rows.Next() {
		var i ListLinksPageRow
		if err := rows.Scan(
			&i.ID,
			&i.OriginalUrl,
			&i.ShortName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLink = `-- name: UpdateLink :one
UPDATE links
SET original_url = $2,
    short_name = $3
WHERE id = $1
RETURNING id, original_url, short_name, created_at
`

type UpdateLinkParams struct {
	ID          int64  `json:"id"`
	OriginalUrl string `json:"original_url"`
	ShortName   string `json:"short_name"`
}

type UpdateLinkRow struct {
	ID          int64     `json:"id"`
	OriginalUrl string    `json:"original_url"`
	ShortName   string    `json:"short_name"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error) {
	row := q.db.QueryRowContext(ctx, updateLink, arg.ID, arg.OriginalUrl, arg.ShortName)
	var i UpdateLinkRow
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.ShortName,
		&i.CreatedAt,
	)
	return i, err
}
