// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateLink(ctx context.Context, arg CreateLinkParams) (CreateLinkRow, error)
	DeleteLink(ctx context.Context, id int64) (int64, error)
	GetLink(ctx context.Context, id int64) (GetLinkRow, error)
	ListLinks(ctx context.Context) ([]ListLinksRow, error)
	UpdateLink(ctx context.Context, arg UpdateLinkParams) (UpdateLinkRow, error)
}

var _ Querier = (*Queries)(nil)
